# Generated by Django 4.0 on 2022-01-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='files',
        ),
        migrations.AlterField(
            model_name='ticketimage',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='ticket_files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='warehousereply',
            name='files',
            field=models.FileField(blank=True, upload_to='home/dzhig/OurSight.com/src/files/media'),
        ),
    ]
