# Generated by Django 4.0 on 2022-01-08 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tickets_files_alter_ticketimage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='completed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 8, 21, 45, 44, 214090)),
            preserve_default=False,
        ),
    ]
