# Generated by Django 4.0 on 2022-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tickets_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
