# Generated by Django 4.0 on 2022-01-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tickets_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticketimage',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketimage',
            name='ticket',
            field=models.ManyToManyField(blank=True, to='main.Tickets'),
        ),
    ]
