# Generated by Django 4.0 on 2022-01-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ticketimage_options_remove_ticketimage_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketimage',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='warehousereply',
            name='files',
            field=models.FileField(blank=True, upload_to='home/dzhig/warehouse_man/warehouse_manager/files/media'),
        ),
    ]
