# Generated by Django 4.0 on 2022-01-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticketimage_external_url_alter_warehousereply_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousereply',
            name='files',
        ),
        migrations.AlterField(
            model_name='ticketimage',
            name='ticket',
            field=models.ManyToManyField(to='main.Tickets'),
        ),
        migrations.CreateModel(
            name='ReplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='replyfiles/%Y/%m/%d')),
                ('reply', models.ManyToManyField(to='main.WarehouseReply')),
            ],
        ),
    ]
