# Generated by Django 4.0 on 2022-01-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_warehousereply_files_alter_ticketimage_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
