# Generated by Django 4.0 on 2022-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tickets_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=500)),
                ('expiary_date', models.DateTimeField(blank=True)),
                ('login_time', models.DateTimeField()),
            ],
        ),
    ]
