# Generated by Django 4.0 on 2022-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rrtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrtoken',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
