# Generated by Django 4.0 on 2022-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_rrtoken_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrtoken',
            name='expiary_date',
            field=models.CharField(max_length=6),
        ),
    ]
